//@flow
import { FOLDER_TYPE, FILE_TYPE } from 'constants/variables';
import cardImage from 'assets/image/Colleagues_looking_at_information_on_mobile_phone_screen_Videos_Mixkit.png';
import {
  FixImageType,
  UnknownType,
  VideoSequencesType,
} from 'helpers/thumbnailSelector';
import sequencesImage from 'assets/image/thumb_scrub.jpg';
import folderThumbnail1 from 'assets/image/folder-thumbnail-1.jpg';
import folderThumbnail2 from 'assets/image/folder-thumbnail-2.jpg';
import folderThumbnail3 from 'assets/image/folder-thumbnail-3.jpg';
import folderThumbnail4 from 'assets/image/folder-thumbnail-4.jpg';
import folderThumbnail5 from 'assets/image/folder-thumbnail-5.jpg';
import itemThumbnail1 from 'assets/image/item-thumbnail-1.jpg';
import itemThumbnail2 from 'assets/image/item-thumbnail-2.jpg';
import itemThumbnail3 from 'assets/image/item-thumbnail-3.jpg';

export default {
  '0': {
    type: FOLDER_TYPE,
    name: 'Hiking Experience ndfsnfnskfdnsjfdnwjfn',
    fileCount: 0,
    thumbnails: [],
    customOrder: 1,
    size: '164 MB',
    uploader: 'Emily Parkson jshdbfhjsdbvhbjhdsbvjhdbs',
    uploadDate: 1573879419000,
  },
  '1': {
    type: FOLDER_TYPE,
    name: 'Going into mountains Experience',
    fileCount: 1,
    thumbnails: [folderThumbnail1],
    customOrder: 2,
    size: '16 MB',
    uploader: 'Emily Parkson',
    uploadDate: 1563249015000,
  },
  '2': {
    type: FOLDER_TYPE,
    name: 'Sea is very good did you know',
    fileCount: 2,
    thumbnails: [folderThumbnail1, folderThumbnail2],
    customOrder: 3,
    size: '16 MB',
    uploader: 'Emily Parkson',
    uploadDate: 1571264553000,
  },
  '3': {
    type: FOLDER_TYPE,
    name: 'This is very good title',
    fileCount: 3,
    thumbnails: [folderThumbnail2, folderThumbnail1, folderThumbnail3],
    customOrder: 4,
    size: '16 MB',
    uploader: 'Emily Parkson',
    uploadDate: 1573891233000,
  },
  '4': {
    type: FOLDER_TYPE,
    name: 'I love foods',
    fileCount: 4,
    thumbnails: [
      folderThumbnail4,
      folderThumbnail3,
      folderThumbnail1,
      folderThumbnail2,
    ],
    customOrder: 5,
    size: '16 MB',
    uploader: 'Emily Parkson',
    uploadDate: 1573891233000,
  },
  '5': {
    type: FOLDER_TYPE,
    name: 'A very very very very so so long title',
    fileCount: 5,
    thumbnails: [
      folderThumbnail3,
      folderThumbnail2,
      folderThumbnail1,
      folderThumbnail4,
      folderThumbnail5,
    ],
    customOrder: 6,
    size: '16 MB',
    uploader: 'Emily Parkson',
    uploadDate: 1573891233000,
  },
  '6': {
    type: FOLDER_TYPE,
    name: 'Ow Im so tired now',
    fileCount: 6,
    thumbnails: [
      folderThumbnail3,
      folderThumbnail2,
      folderThumbnail1,
      folderThumbnail5,
      folderThumbnail4,
    ],
    customOrder: 7,
    size: '16 MB',
    uploader: 'Emily Parkson',
    uploadDate: 1573891233000,
  },
  '7': {
    type: FILE_TYPE,
    status: { caption: 'In Progress', color: '#64a7ff' },
    version: 2,
    thumbnailType: FixImageType,
    thumbnail: { thumbnailSrc: itemThumbnail1 },
    size: '16 MB',
    commentsCount: 6,
    assetName: 'Day10-month 12-halllow',
    assetExtension: 'jpg',
    customOrder: 8,
    uploader: 'Emily Parkson',
    fileUploadDate: 1531713015000,
  },
  '8': {
    type: FILE_TYPE,
    status: { caption: 'Done', color: '#00ffa7' },
    version: 200,
    thumbnailType: VideoSequencesType,
    thumbnail: {
      sequencesSrc: sequencesImage,
      sequencesCount: 50,
      sequenceSize: { width: 240, height: 135 },
    },
    size: '16 MB',
    commentsCount: 999,
    assetName: 'Day10-month 12-halllow',
    assetExtension: 'mp4',
    customOrder: 9,
    uploader: 'Emily Parkson',
    fileUploadDate: 1531713015000,
  },
  '9': {
    type: FILE_TYPE,
    status: { caption: 'In Review', color: '#ffcc00' },
    version: 2,
    thumbnailType: FixImageType,
    thumbnail: { thumbnailSrc: itemThumbnail2 },
    size: '16 MB',
    commentsCount: 6,
    assetName: 'Day10-month 12-halllow',
    assetExtension: 'jpg',
    customOrder: 10,
    uploader: 'Emily Parkson',
    fileUploadDate: 1531713015000,
  },
  '10': {
    type: FILE_TYPE,
    status: { caption: 'In Review', color: '#ffcc00' },
    version: 2,
    thumbnailType: UnknownType,
    size: '16 MB',
    commentsCount: 6,
    assetName: 'Day10-month 12-halllow',
    assetExtension: 'pdf',
    customOrder: 11,
    uploader: 'Emily Parkson',
    fileUploadDate: 1550811015000,
  },
  '11': {
    type: FILE_TYPE,
    version: 2,
    thumbnailType: FixImageType,
    thumbnail: { thumbnailSrc: itemThumbnail3 },
    size: '16 MB',
    commentsCount: 6,
    assetName: 'Day10-month 12-halllow',
    assetExtension: 'raw',
    customOrder: 12,
    uploader: 'Emily Parkson',
    fileUploadDate: 1553277015000,
  },
  '12': {
    type: FILE_TYPE,
    status: { caption: 'Done', color: '#00ffa7' },
    version: 22,
    thumbnailType: UnknownType,
    thumbnail: { thumbnailSrc: cardImage },
    size: '16 MB',
    commentsCount: 6,
    assetName: 'Day10-month 12-halllow',
    assetExtension: '3rd',
    customOrder: 13,
    uploader: 'Emily Parkson',
    fileUploadDate: 1553277015000,
  },
  '13': {
    type: FILE_TYPE,
    version: 2,
    thumbnailType: FixImageType,
    thumbnail: { thumbnailSrc: cardImage },
    size: '16 MB',
    commentsCount: 6,
    assetName: 'Day10-month 12-halllow',
    assetExtension: 'jpg',
    customOrder: 14,
    uploader: 'Emily Parkson',
    fileUploadDate: 1553277015000,
  },
};
