import image1 from 'assets/image/christopher-campbell-rDEOVtE7vOs-unsplash.png';
import image2 from 'assets/image/christopher-campbell-rDEOVtE7vOs-unsplash.png';
import image3 from 'assets/image/christopher-campbell-rDEOVtE7vOs-unsplash.png';
const testData = [
  {
    avatarSrc: '',
    shortName: 'SP',
    name: '1Sara Parker',
    createdAt: 1571295775000,
    text: 'Uploaded "aportman family"',
    avatarColor: 'gray',
  },
  {
    avatarSrc: image2,
    name: '2Amili Hilton',
    shortName: 'AH',
    createdAt: 1571209375000,
    text: 'Removed 3 files',
    avatarColor: '#fff',
  },
  {
    avatarSrc: image3,
    name: '3Andrew Sunny',
    shortName: 'AS',
    createdAt: 1571209375000,
    text: 'Shared "aportman family" with Peter Brown.',
    avatarColor: '#fff',
  },
  {
    avatarSrc: image1,
    name: '4Pablo Neroda',
    shortName: 'PN',
    createdAt: 1571027260000,
    text: 'Commented on "winter fall"',
    avatarColor: '#fff',
  },
  {
    avatarSrc: image1,
    name: '5Pablo Neroda',
    createdAt: 1571016460000,
    text: 'Commented on "winter fall"',
    shortName: 'PN',
    avatarColor: '#fff',
  },
  {
    avatarSrc: image1,
    name: '6Pablo Neroda',
    shortName: 'PN',
    createdAt: 1571009260000,
    text: 'Commented on "winter fall"',
    avatarColor: '#fff',
  },
  {
    avatarSrc: image1,
    name: '7Pablo Neroda',
    shortName: 'PN',
    createdAt: 1571002060000,
    text: 'Commented on "winter fall"',
    avatarColor: '#fff',
  },
  {
    avatarSrc: image1,
    name: '8Pablo Neroda',
    shortName: 'PN',
    createdAt: 1570963070000,
    text: 'Commented on "winter fall"',
    avatarColor: '#fff',
  },
  {
    avatarSrc: image1,
    name: '8Pablo Neroda',
    ShortName: 'PN',
    createdAt: 1570955870000,
    text: 'Commented on "winter fall"',
    color: '#fff',
  },
  {
    avatarSrc: image1,
    name: '9Pablo Neroda',
    ShortName: 'PN',
    createdAt: 1570836460000,
    text: 'Commented on "winter fall"',
    color: '#fff',
  },
];
export default testData;
